#!/usr/bin/env bash

#####################################
#                                   #
#  @author      : 00xWolf           #
#    GitHub    : @mmsaeed509       #
#    Developer : Mahmoud Mohamed   #
#  﫥  Copyright : Exodia OS        #
#                                   #
#####################################

##  ----- Dual monitor setup -----  ##
#
# run `xrandr -q | grep " connected" | cut -d ' ' -f1`   to list monitors
# in my case eDP1 , HDMI-1-0
# change 'HDMI-1-0' to your output
 
if [[ $(xrandr -q | grep 'HDMI-1-0 connected') ]]; then

 		# use arandr or xrandr to set monitors config
 		# in my case, i use laptop monitor (eDP1) as Primary display 
 		# and the second monitor (HDMI-1-0) as external display (extended to right)
		# add your config to this directory `~/.config/bspwm/bin/` , If it doesn't exist, create one
		mainLeftExternalRight
		# mainDownExternaUp
		# mainDownExternaMAINUp
		# mainLeftExternaMAINRight
		  
fi
