#!/bin/sh

#
# Copyright (C) 2022 Mahmoud Mohamed (00xWolf)  <https://github.com/mmsaeed509>
# LICENSE © GNU-GPL3
#

## ------------ COLORS ------------ ##

# Reset #
RESET_COLOR='\033[0m' # Text Reset

# Regular Colors #
Black='\033[0;30m'  Red='\033[0;31m'     Green='\033[0;32m'  Yellow='\033[0;33m'
Blue='\033[0;34m'   Purple='\033[0;35m'  Cyan='\033[0;36m'   White='\033[0;37m'

# Bold #
BBlack='\033[1;30m' BRed='\033[1;31m'    BGreen='\033[1;32m' BYellow='\033[1;33m'
BBlue='\033[1;34m'  BPurple='\033[1;35m' BCyan='\033[1;36m'  BWhite='\033[1;37m'

# Underline #
UBlack='\033[4;30m' URed='\033[4;31m'    UGreen='\033[4;32m' UYellow='\033[4;33m'
UBlue='\033[4;34m'  UPurple='\033[4;35m' UCyan='\033[4;36m'  UWhite='\033[4;37m'

# Background #
On_Black='\033[40m' On_Red='\033[41m'    On_Green='\033[42m' On_Yellow='\033[43m'
On_Blue='\033[44m'  On_Purple='\033[45m' On_Cyan='\033[46m'  On_White='\033[47m'

heatSensors=$(sensors | grep -m 1 id | awk '{print substr($4, 2, length($4)-5)}')

# from  0°C to 40°C print ->  
if [[ "$heatSensors" -le 40 ]] 
	then
		# the ' %{T3} ' -> pass font type to polybar config file 
		# the selected font type is number 3, which is (font-3 = "Iosevka:style=bold:"size=12;3" )
		echo -e " $heatSensors°C"

# from 40°C to 60°C print -> 
elif [[ "$heatSensors" -le 60 ]] 
	then
		echo -e " $heatSensors°C"

# from 60°C to 85°C print -> 
elif [[ "$heatSensors" -le 85 ]]
	then
		echo -e " $heatSensors°C"

# from 85°C to +... print ->  
elif [[ "$heatSensors" -gt 85 ]] 
	then
		# the  ' -n "%{F#FF0008}"  ' -> red font as 85°C to +... is the default warn temperature
		echo -e "${BRed} $heatSensors°C"
fi
